on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production
jobs:
  build:
    uses: webpros-cpanel/ea-tools/.github/workflows/reusable-obs-build.yml@ghes
    secrets: inherit
